baseurl = "/"
languageCode = "en-us"
title = "Bryan's website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "bryanshalloway"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/brshallo"
    weight = 2
[[menu.main]]
    name = "GitHub"
    identifier = "github"
    url = "https://github.com/brshallo"
    weight = 3
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/bryanshalloway/"
    weight = 4
[[menu.main]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCDVMC4-VRU-tR2Z4nYc1mDA"
    weight = 5

[params]
    description = "A personal website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "bryan_edit.jpg"
    width = 50
    height = 50
    alt = "Logo"

