baseurl = "https://www.bryanshalloway.com/"
languageCode = "en-us"
title = "Bryan Shalloway's Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "bryanshalloway"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/brshallo"
    weight = 2
[[menu.main]]
    name = "GitHub"
    identifier = "github"
    url = "https://github.com/brshallo"
    weight = 3
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/bryanshalloway/"
    weight = 4
[[menu.main]]
    name = "YouTube"
    url = "https://www.youtube.com/watch?v=gme4Fb9JVjk&list=PL2f6B79nBqL16QFte8fN_GWDtJwZDXt95"
    weight = 5

[params]
    summary_length = 200
    description = "Bryan Shalloway's website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    # Set to true to disable code folding
    disable_codefolding = false
    # Set to "hide" or "show" all codes by default
    codefolding_show = "show"
    # Set to true to exclude the "Show/hide all" button
    codefolding_nobutton = false
    custom_css = ["codefolding.css"]

    [params.logo]
    url = "bryan_edit.jpg"
    width = 60
    height = 60
    alt = "Logo"
    