---
title: A National Popular Vote Weighted by the Electoral College
author: Bryan Shalloway
date: '2020-09-11'
categories:
  - politics
tags:
  - data journalism
  - electoral college
  - popular vote
slug: compromise-between-the-electoral-college-and-a-national-popular-vote
output:
  blogdown::html_page:
    toc: no
---

*In this post I discuss using a national popular vote weighted by the electoral college for presidential elections. This approach would empower voters by expanding political influence outside of ‘battleground states.’ It would also preserve the existing biases built into the American electoral college (thereby making such a system legislatively palatable across party affiliations). This post presents some potential merits of a weighted national popular vote -- it does not represent an endorsement.*

Irrespective of political party or disposition towards direct democracy, the winner-take-all approach (currently applied by most US states to allocate their electoral votes for the president) has clear drawbacks. These include:

* incentivizes presidential candidates only campaigning in battleground states
* greater variability in outcomes compared to alternatives^[A few thousand votes in a few places have a greater chance of swaying entire elections in our current system compared to alternatives.]
* incentivizes promoting policies that benefit battleground states over the interests of ‘all Americans’
* promotes a feeling among much of the electorate that their vote is unlikely to influence the election

In the last four years, the movement to change the election of the president to a national popular vote has gained traction. A compact between states to vote for the national popular vote winner has been passed in states representing 196 of the 270 electoral votes required for the agreement to have legal force. The website promoting the [National Popular Vote](https://www.nationalpopularvote.com/) initiative outlines the disadvantages of the winner-take-all approach used by most states and provides arguments for employing a national popular vote. The site also provides evidence for the constitutionality of a national popular vote (debunking straw-man arguments against it) and counters ‘myths’^[‘myths,’ is the terminology used on their website] that a popular vote would overly advantage or disadvantage certain states.

However a major challenge in transitioning to a popular vote is that, for any given presidential election cycle, the electoral college may favor a particular political party. Hence it would be against the advantaged party’s interests^[at least their interests in winning the presidential election] to support a change to the election process (likewise, the disadvantaged party has an incentive to support a change in the election process^[It’s not a coincidence that the popular vote initiative is currently supported primarily be Democrats.]). Therefore a cynic could argue that getting the requisite number of states to legislate support for the national popular vote is almost synonymous with winning the election. Furthermore, legislation for a national popular vote that was passed into law could be politically fragile (and may be at risk of frequent challenges depending on the state-level political party in power).

The goal of the National Popular Vote initiative is to *make every vote matter equally*. However if we weaken this goal to be: *make the importance of votes more equal than they currently are,* ^[by spreading political influence away from the dozen or so battleground states] it may be easier to change the electoral system in a way that is less likely to agitate partisans^[or those attached to the traditional influence of the electoral college on presidential elections.]. 

I believe a popular vote *weighted by the electoral college* deserves consideration. Such an approach is equivalent to having the allocation of electoral votes in each state be based on the popular vote within that state. For example, if a state has 30 electoral votes, and 55% of those go to the Republican and 45% to the Democrat, the Republican would receive 16.5 votes and the Democrat 13.5^[“Proportional (fractional) allocation of electoral votes by state” (in the form described in this post) is the same as “popular vote weighted by electoral college”. Throughout this post however I will use the latter terminology.].

This approach would empower small states whose voters' ballots would be essentially worth double that of those in large states^[https://theconversation.com/whose-votes-count-the-least-in-the-electoral-college-74280]. While this may seem horribly unfair, it only makes the existing biases built into the electoral college more transparent. Also^[regardless of your opinion on the electoral college and whether voters in small states *should* be afforded outsized representation compared to their population.], it still represents a major improvement in representativeness over the existing system -- where only a ~quarter of the population’s votes make any substantitive difference in the outcome of the election (specifically those votes in battleground states^[“Influence" here is evidenced by campaign events and ad spending among candidates as described [here](https://www.nationalpopularvote.com/written-explanation).]). 

A weighted national popular vote would likely preserve (at least in part) any advantage a party has in the electoral college for a given election cycle. This would make associated legislation potentially more palatable and enduring across changes in state-level leadership (compared to legislation for a raw popular vote). The weighted popular vote also maintains the essence of the existing electoral college^[I.e. it still spreads out votes by states and not just across the population] -- it just replaces 'winner-take-all' with 'proportional' allocation of a state's electoral votes (perhaps a less glaring difference compared to adopting a raw national popular vote).

Since 1976 there have been two elections where the popular vote and the electoral college did not agree. The weighted national popular vote would have disagreed with the national popular vote once (in the 2000 election) and with the winner-take-all electoral college once (in 2016)^[In 2016 Clinton would have had a ~1 percentage point advantage over Trump in the weighted popular vote (compared to the ~2 percentage point advantage she had in the raw popular vote). Under the weighted popular vote George W. Bush would still have still won the election in 2000, despite losing the raw popular vote.]. See script in my github repo [brshallo/weighted-national-popular-vote](https://github.com/brshallo/weighted-national-popular-vote) for details on data sources and how the national weighted popular vote was calculated.

# How to get it passed?

The beginning of the video “Myths About Constitutionality” explains how we got our current ‘winner-take-all’ systems across states. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/ubIeQ-uO_b0?start=92" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Essentially it was a [collective action problem](https://en.wikipedia.org/wiki/Collective_action_problem#:~:text=A%20collective%20action%20problem%20or,individuals%20that%20discourage%20joint%20action.) whereby states (controlled by one party or another) adopted a ‘winner-take-all’ approach as a means of maximizing their influence and giving the most advantage they could to their preferred candidate. Once a few states adopted the ‘winner-take-all’ system it created a domino effect whereby all states adopted it^[The result of every state adopting it however has resulted in the majority of states' influence being reduced.]. 

Ways of getting around this collective action problem:

*	The approach the National Popular Vote initiative has used is to have individual states pass laws that only go into effect once the requisite threshold of electoral votes is reached – thereby not forcing any individual state to ‘give-up’ some of their influence prematurely. The same approach could be taken to push adoption of a weighted national popular vote^[I.e. the law would only go into effect when states representing 270 electoral votes passed legislation.].
*	Other approaches could be more piecemeal. For example states of similar size and counterbalanced political leanings agree to pass proportional voting laws simultaneously – thereby not damaging the interests of their preferred presidential candidate (but still empowering the voters within their state)^[E.g. say a ten vote state that tends to go 60% democratic teams up with another ten vote state that tends to go 60% republican and each pass a proportional voting system simultaneously.]. Such an approach would be more effective if fractional votes among electors is allowed^[Interesting article on fractional representatives: http://www.hnn.us/articles/129114.html .].
*	A third approach would be an amendment to the US constitution.

# Closing note

The chief advantage of a national popular vote for presidential elections is not that it achieves *perfect* representation but that it provides *improved incentives* for presidential candidates. Specifically it promotes campaigns and policy proposals that give attention to a broader subset of the American public^[As described [here]( https://www.nationalpopularvote.com/written-explanation)).] and reduces the variability in election results. However a national popular vote inevitably faces partisan challenges and may give-off the appearance of too momentous a departure from the norms of the existing electoral college. As a compromise between these systems, a national popular vote, that is weighted by the electoral college, avoids many of the challenges to legislating a pure national popular vote while still achieving its most important objectives.

# Appendix

## What about Nebraska and Maine?

> In all but two states, electoral votes are 'winner-take-all'. The candidate winning the popular vote normally receives all of that state's votes. Maine and Nebraska have taken a different approach. Using the 'congressional district method', these states allocate two electoral votes to the state popular vote winner, and then one electoral vote to the popular vote winner in each Congressional district (2 in Maine, 3 in Nebraska). This creates multiple popular vote contests in these states, which could lead to a split electoral vote.
> - https://www.270towin.com/content/split-electoral-votes-maine-and-nebraska/

There may be some philosophical appeal to this method for allocating votes however there are still relatively similar problems with it to the ‘winner-take-all’ method when applied to the state. For example, 

*	if your vote is not in a ‘battleground district’ your vote, once again, may not matter as much (i.e. a ‘battleground state’ is simply replaced by a ‘battleground district’)
*	opens-up presidential election to risks associated with gerrymandering
*	if this were applied nationally, appealing to specific states could be supplanted by appealing to specific types of congressional districts, e.g. districts with more urban or rural areas (which may influence president’s against ‘looking out for all Americans’)
