---
title: Solar in Seattle
author: Bryan Shalloway
date: '2023-02-02'
slug: solar-in-seattle
categories:
  - politics
tags: []
thumbnail: /2023/02/02/solar-in-seattle/images/bill-mead-wmaP3Tl80ww-unsplash.jpg
---

**TLDR:** Residential solar installations have gained popularity in the Seattle area over the last few years[^Anecdotal]. Prima facie, these represent a suboptimal use of panels which could be more productive in regions of the country that are less overcast or have greater energy demands. The common inclination to "act locally" is sometimes misguided.  Climate change and personal investments are global topics; decision making concerning them should be treated as such[^grain-of-salt].

[^grain-of-salt]: This post is more "hot take" than researched evaluation of solar and green energy investments. Most of my sources are just a mash-up of things I maybe read somewhere and intuition, rather than a thorough review of literature.

Anyone who lives in a residential area in Seattle has likely seen [this](https://www.youtube.com/watch?v=0StcKgAWnu4), [this](https://www.youtube.com/watch?v=MdbA_Q8AEGA), or similar ads for home solar installations. These elide the problem that Seattle is a comparatively bad candidate for residential solar:

* Our energy is relatively cheap.
* It already mostly comes from renewable sources (particularly hydroelectric).
* Local installation/service costs are high. 
* The city is notoriously overcast[^sun-islands]. 

Determining whether to invest in residential solar panels is not about if it will break-even but whether it offers greater returns and greenhouse gas reductions than other potential projects -- i.e. you should consider the Opportunity Cost of the investment. 

Seattle gets ~2170 sunshine hours per year^[See [wikipedia's](https://en.wikipedia.org/wiki/List_of_cities_by_sunshine_duration) list of cities by sun duration.]. This is ~41% less than San Diego and ~78% less than Phoenix. Regions in the Northeast can also be good places for solar. For example Boston, while not known for it's sunshine, gets a large proportion of its energy from fossil fuels and has energy costs nearly double those in Seattle. Hence, for reasons different from the sunbelt, regions with high energy costs or a heavy reliance on fossil fuels may also be better prospects for solar than Seattle^[With a "smart grid" that was better able to transmit energy, you could have the sunbelt solar energy power the Northeast in which case unmet energy demands may be less pressing than optimizing on energy production.]. 

The stark differences in solar panel productivity and energy costs across different regions of the country presents a pseudo-arbitrage opportunity. If the Seattle panels were installed in regions with more sun or greater energy demand, they could be more productive[^gaps]. I am oversimplifying[^details]; yet a closer examination of local electrical grids, panel productivity, etc. seems unlikely to lead to a conclusion that Seattleites should be putting solar panels on their roofs[^currently] -- at least not while better candidates have excess space for panels^[WARNING: I did not actually look much into whether these are true facts about the state of "prime" candidates for solar panel installations.]. Hence, if you are a climate conscious person living in Seattle with ~$30K sitting around, there are likely better options than your roof for investing in solar or other renewable energies[^but-why]. 

**Diversify your portfolio**

The typical American already has a disproportionate share of their wealth tied-up in their home. There is a certain logic to this centralization; people use and enjoy the space where they live -- remodeling your kitchen is *more* than just a capital investment in real estate. However you can't, in any substantive sense, use solar panels to add value to your day-to-day life[^exception]. Hence, most Americans should be slightly disinclined toward investments that further concentrate their portfolio of assets[^on-offer]. There are many other ways to get involved in the solar industry that don't involve adding solar panels to your cloud-covered Seattle home. 

[^on-offer]: Even though you can see the physical panels on your home, you can't use them. Hence, in many ways, you should consider solar panels like how you consider investments in stocks or bonds or other non-tangible places where you put your money. However, they are attached to your house and require upkeep and will affect your home when you go to sell it, so they are still intricately linked to the investment in your home.

**What should the Seattle solar-phile do?**

If Seattleites want to be a part of the growth of solar, they may be better off funding projects elsewhere. One idea might be to call your aunt in Southern California and offer to finance her panels[^payments]. Similarly, you could lease out the space on her roof and then buy and install your own panels[^leasing]. A problem with these sorts of arrangements is they get complicated when things change. What if she moves^[how do the contracts tie into the mortgage…?], the panels get damaged, someone stops paying ...? These complexities are likely why solar panel financing is dominated by corporations and banks rather than peer-to-peer platforms. That rooftop leasing mostly doesn't exist in Seattle^[[Google Project Sunroof](https://sunroof.withgoogle.com/) suggests leasing out your roof is an option in Seattle but that the fees are greater than the returns.] is a tell that residential solar panel installations may not be as profitable (or at least as risk-free) as the mass of online ads make them sound[^in-cali]. 

Compared to trying to establish "remote" residential solar installations, ventures in solar farms/collectives/community owned panels are perhaps easier, lower risk options for an individual investor[^residential]. Solar farms are also more efficient than residential installs. Furthermore the minimum capital from each investor may be less than the price of a residential installation[^resident]. This provides a path to invest for those who don't own their home or are unable to afford an installation on their personal residence. 

If one solar farm is good, many may be better^[Diversification is good!]. Rather than invest a stake in a single farm you could purchase equity in solar companies or bonds for solar operations that span many projects. There are also index funds and other financial instruments that track solar power^[e.g.SUNIDX]. The global suite of financial services and investment markets are at your fingertips; exploring these in the context of the renewable energy industry can be an outlet for the *personal energy* of a Seattle solar-phile. 

**Individual action**

If your interest in solar is primarily as a means to reduce your personal carbon footprint^[There's also the argument that you shouldn't try to offset your personal carbon footprint as much as you should just try to offset as much carbon as possible, regardless of your personal behavior.] you might instead purchase carbon offsets, donate to [effective charities](https://www.effectiveenvironmentalism.org/climate-charities) who focus on climate change, advocate to politicians to expand or open new renewable energy sources, or a myriad of other (non-investment) forms of engagement. When evaluating carbon conscious local home improvements, you ought to take into account the comparative advantage associated with your region, home, or interests^[/How you spend your time.]. For example, heat pumps (which can replace a furnace and AC) work especially well in mild climates like Seattle's. If you have a spare bedroom or basement you might rent it out (higher density regions tend to contribute to lower per capita emissions). If your work involves driving, you might purchase an electric vehicle. I haven't run the numbers on any of these examples^[Depending on your local grid and situation it may be more effective to just purchase carbon offsets to reduce your footprint and hold-off on going electric.] but for any option you should...

1. take into account your specific circumstances 
1. compare it against alternatives, including both real (e.g. physical change to a home) and financial (e.g. stocks, bonds) assets^[Both climate change and your investment portfolio are topics to be examined in a global context; it is important to consider the full range of options available to you and not get hung-up on thinking *just* in terms of your personal consumption or physical modifications you can make to your home.]
1. evaluate it on a standard scale of financial and environmental returns on investment

With a variety of green investment options available, it's important to maintain a shrewd perspective and choose the ones that optimize upon your goals[^action]. Investing in a cleaner future has never been easier or more important; I encourage you to take an active and thoughtful role in its development.

[^Anecdotal]: Touring around the city I regularly see residential solar installations. When I ask friends/family what they think about getting solar more of them say "I want to!" I didn't do a thorough review hence this statement is largely vibes based. According to [[Google Project Sunroof](https://sunroof.withgoogle.com/) total installations are still a small fraction of what they are in California. What we *do* get a ton of in Seattle is ads for solar installations. 

[^sun-islands]: There are also lots of shade creating trees. It is worth noting that there are “sun islands” not too far from Seattle that get substantially less cloud coverage. For example Whidbey Island (35 mile drive and just off the coast). The cool, temperate Seattle climate also has some advantages for panel efficiency.

[^details]: I'm ignoring things like local regulatory environments and incentive structures, risks of too much surplus energy for the grid to handle in the summer and limitations with transporting energy on the grid, market responses to energy production, panel performance at different temperatures etc. etc.

[^gaps]: Seattle has cheaper per kilowatt energy costs.

[^currently]: Again, I am saying *at this time*. Once the “prime” solar panel locations are all filled-up in other regions and costs continue to come down, it could make more sense to expand solar to Seattle, but Seattleites should likely be near the back of the line... residential installations even more so. 

[^but-why]: I won't focus so much on why residents choose to install solar in Seattle -- this post is more "hot take" than vigorous review. Some guesses for explanations: effective marketing by installers, generous incentives, wealthy/credulous/virtue signaling/well-meaning home owners, survivalist home owners, or, quite likely, I am missing something…

[^payments]: If the payments she makes to you each month are greater than what you’d save with panels in Seattle, that’s a win for you. If those payments are less than she makes from the panels, that’s a win for her. 

[^leasing]: You now own the panels directly and can collect whatever profits you make from the power supplied to her or the local grid. She might be more on-board with this option as she’s no longer (as directly) shouldering the risk of the investment.

[^in-cali]: In California I think you *do see* zero cost rooftop leasing programs where residents are able to get paid to lease out their rooftops for solar installations -- though they seem to be dominated by larger buildings less so than residential installs and I haven't looked into whether these are legit.

[^residential]: All of this does not take into account the complexity and costs of residential installations themselves (e.g. connecting to the grid, pulling permits, etc.).

[^resident]: One challenge is that some of these may be geographically restricted, i.e. if you don’t live in the community, you aren’t allowed to buy a share in the solar farm. While this may not be ideal in a normative sense and unfortunate for the interested Seattle Solar-phile investor, such local preference policies can be a helpful way of getting communities on-board with solar projects in their neighborhood -- that otherwise may fight them using local bureaucratic measures.

[^exception]: There are exceptions to this. For example, if you can use solar to give you back-up power in the case of a power outage, this is a functionality you can use and isn't just a number on a monthly bill. HOWEVER, this feature typically requires additional systems to set-up and is not enabled by most residential solar installs. 

[^action]: I mean this post as a call to action, not an excuse for inaction. The take away is not “Solar panels seem not to make sense in Seattle, so I’m going to abandon my intended project and not going do anything,” but, “Wow, there are so many great alternatives available, therefore I am even more excited about other more impactful ways for me to invest in renewable energy.”